#ifndef FEATURE_H
#define FEATURE_H

#define AUTO_REGEX_PARSE
#undef MANUAL_REGEX_PARSE

// #define MANUAL_REGEX_PARSE
// #undef AUTO_REGEX_PARSE

#define AUTO_LEX_PARSE
#undef MANUAL_LEX_PARSE

#endif // !FEATURE_H
